#!/usr/bin/env python3
"""Crop the 36 KORD BREACH block PNGs down to their icon, key it out to alpha,
and emit both icons/*.png and a data-URI map in icons.js.

Run from web/:   python3 build_icons.py

Why data URIs: Chrome refuses to fetch a CSS mask-image over file://, so the
icons render as blank boxes if you just double-click index.html with relative
paths. Inlining sidesteps that and makes the page self-contained.
"""
import base64
import glob
import os

import numpy as np
from PIL import Image

SRC = '../source/blocks'
OUT_DIR = 'icons'
OUT_JS = 'icons.js'

# The icon sits at rows 21..93, cols 17..93 of every card. This 94x94 box is
# centred on it with a few px of margin, and stops short of the Korean
# subtitle overlay that starts around y=95 on the taller crops.
BOX = (8, 10, 102, 104)


def keyed_alpha(path: str) -> Image.Image:
    """White line-art on a dark hatched plate -> white RGB + luminance alpha."""
    full = np.array(Image.open(path).convert('L'), dtype=float)
    # Threshold from the whole card, not the crop: the crop is mostly icon, so
    # its own histogram would put the noise floor way too high.
    bg = full[full <= np.percentile(full, 60)]
    t0 = bg.mean() + 4.0 * bg.std()          # hatch texture -> fully transparent
    lum = full[BOX[1]:BOX[3], BOX[0]:BOX[2]]
    t1 = np.percentile(lum, 99.0)            # brightest stroke -> fully opaque
    alpha = (np.clip((lum - t0) / max(t1 - t0, 1e-6), 0, 1) * 255).astype(np.uint8)

    rgba = np.zeros((*lum.shape, 4), np.uint8)
    rgba[..., :3] = 255                      # white; tinted per-category via CSS
    rgba[..., 3] = alpha
    return Image.fromarray(rgba, 'RGBA')


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    files = sorted(glob.glob(f'{SRC}/*.png'))
    if len(files) != 36:
        raise SystemExit(f'expected 36 blocks in {SRC}, found {len(files)}')

    rows, total = [], 0
    for path in files:
        name = os.path.basename(path)
        icon = keyed_alpha(path)
        dst = os.path.join(OUT_DIR, name)
        icon.save(dst, optimize=True)

        b64 = base64.b64encode(open(dst, 'rb').read()).decode()
        total += len(b64)
        rows.append(f"  {int(name[:2])}: 'data:image/png;base64,{b64}',")

    with open(OUT_JS, 'w') as fh:
        fh.write(
            f'// GENERATED by build_icons.py — do not edit. Source: {SRC}/*.png\n'
            '//\n'
            '// Icons are inlined as data URIs on purpose: Chrome will not fetch a\n'
            '// mask-image over file://, so relative icon paths render as blank boxes\n'
            '// when you just double-click index.html. Inlining also makes the page\n'
            '// self-contained for GitHub Pages / Artifact deploys.\n'
            'const ICON_URI = {\n' + '\n'.join(rows) + '\n};\n'
        )
    print(f'{len(files)} icons -> {OUT_DIR}/ and {OUT_JS} ({total / 1024:.0f} KB base64)')


if __name__ == '__main__':
    main()
