#!/usr/bin/env python3
"""Cut the 노잼망겜 mascot out of the promo banner and emit char.js.

Source: the banner image attached to
https://x.com/NoJamMangGameTV/status/2075204198434787502
(saved locally as assets/promo_banner.jpg)

The mascot sits on the banner's flat dark plate. A plain colour threshold would
also erase the character's near-black outline, so the background is removed by
flood-filling inward from the border: only plate pixels *connected to the edge*
are dropped.

Run from web/:   python3 build_char.py
"""
import base64
from collections import deque

import numpy as np
from PIL import Image

SRC = 'assets/promo_banner.jpg'
OUT_PNG = 'assets/character.png'
OUT_JS = 'char.js'

CROP = (0, 0, 268, 247)              # mascot's corner; title text starts at x=267
PLATE = np.array([17, 20, 25])      # banner background
TOL = 55                            # plate + its faint diagonal hatch


def cutout() -> Image.Image:
    rgb = np.array(Image.open(SRC).convert('RGB').crop(CROP)).astype(int)
    h, w, _ = rgb.shape
    plate = np.abs(rgb - PLATE).sum(2) < TOL

    seen = np.zeros((h, w), bool)
    q = deque()
    for x in range(w):
        for y in (0, h - 1):
            if plate[y, x] and not seen[y, x]:
                seen[y, x] = True
                q.append((y, x))
    for y in range(h):
        for x in (0, w - 1):
            if plate[y, x] and not seen[y, x]:
                seen[y, x] = True
                q.append((y, x))
    while q:
        y, x = q.popleft()
        for ny, nx in ((y + 1, x), (y - 1, x), (y, x + 1), (y, x - 1)):
            if 0 <= ny < h and 0 <= nx < w and plate[ny, nx] and not seen[ny, nx]:
                seen[ny, nx] = True
                q.append((ny, nx))

    alpha = np.where(seen, 0, 255).astype(np.uint8)
    img = Image.fromarray(np.dstack([rgb.astype(np.uint8), alpha]), 'RGBA')
    return img.crop(img.getbbox())


def main() -> None:
    img = cutout()
    # flat cel-shaded art: 40 colours is lossless to the eye and ~30% smaller
    keep = img.getchannel('A')
    small = img.convert('RGB').quantize(colors=40, method=Image.MEDIANCUT).convert('RGBA')
    small.putalpha(keep)
    small.save(OUT_PNG, optimize=True)

    b64 = base64.b64encode(open(OUT_PNG, 'rb').read()).decode()
    with open(OUT_JS, 'w') as fh:
        fh.write(
            f'// GENERATED by build_char.py — do not edit. Source: {SRC}\n'
            '// 노잼망겜 mascot, inlined so the page stays self-contained.\n'
            f"const CHARACTER_URI = 'data:image/png;base64,{b64}';\n"
        )
    print(f'{OUT_PNG} {img.size} -> {OUT_JS} ({len(b64) / 1024:.0f} KB base64)')


if __name__ == '__main__':
    main()
